# https://ambar-thecloudgarage.medium.com/remote-writes-with-kube-prometheus-3b4ad038d675
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
    - static_configs:
        - targets:
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
        - prometheus:9090


  - job_name: Pushgateway
    honor_labels: true
    honor_timestamps: true
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs: 
      - targets: ['pushgateway:9091', ]